services:
  - type: web
    name: speech-visualizer-backend
    env: node
    buildCommand: ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production 